-- Run this entire file once in Supabase SQL Editor.
-- It creates the anonymous voting backend used by index.html.

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  choice text not null check (choice in ('stay','away')),
  voter_token uuid not null unique,
  created_at timestamptz not null default now()
);

alter table public.votes enable row level security;

revoke all on table public.votes from anon, authenticated;

create or replace function public.cast_vote(p_choice text, p_voter_token uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_choice not in ('stay','away') then
    raise exception 'invalid choice';
  end if;

  insert into public.votes(choice, voter_token)
  values (p_choice, p_voter_token);
exception
  when unique_violation then
    raise exception 'already voted';
end;
$$;

create or replace function public.get_vote_results()
returns table(choice text, votes bigint)
language sql
security definer
set search_path = public
as $$
  select v.choice, count(*)::bigint as votes
  from public.votes v
  group by v.choice
  order by v.choice;
$$;

revoke all on function public.cast_vote(text, uuid) from public;
grant execute on function public.cast_vote(text, uuid) to anon, authenticated;

revoke all on function public.get_vote_results() from public;
grant execute on function public.get_vote_results() to anon, authenticated;
